title: Doom Demo
logoText: Doom Demo
lang: en
api:
  crds:
    - docs/shared/crds/*.yaml
    - docs/shared/crds/*.yml
  openapis:
    - docs/shared/openapis/**/*.json
    - docs/shared/openapis/**/*.yaml
    - docs/shared/openapis/**/*.yml
permission:
  functionresources:
    - docs/shared/functionresources/*.yaml
  roletemplates:
    - docs/shared/roletemplates/*.yaml